export default [
  {
    source: require('./assets/italian-brainrot/BallerinaCappuccina.jpg'),
    name: 'Ballerina Cappuccina',
    ability: ['ballet'],
    motive: ['Ballerina', 'cappuccino'],
  },
  {
    source: require('./assets/italian-brainrot/BlueberrinniOctopussini.jpg'),
    name: 'Blueberrinni Octopussini',
    ability: ['Scaffolding attack', 'fast swimming'],
    motive: ['Blueberry', 'octopus'],
  },
  {
    source: require('./assets/italian-brainrot/BobritoBandito.jpg'),
    name: 'Bobrito Bandito',
    ability: ['mass shooting'],
    motive: ['Beaver', 'Thompson submachine gun', 'gangster', 'mafia'],
  },
  {
    source: require('./assets/italian-brainrot/BombardiereLucertola.jpg'),
    name: 'Bombardiere Lucertola',
    ability: ['Bomber', 'flight', 'camouflage'],
    motive: ['Bomber', 'lizard'],
  },
  {
    source: require('./assets/italian-brainrot/BombardiroCrocodilo.jpg'),
    name: 'Bombardiro Crocodilo',
    ability: ['Bomber', 'flight'],
    motive: ['Bomber', 'crocodile'],
  },
  {
    source: require('./assets/italian-brainrot/BombombiniGusini.jpg'),
    name: 'Bombombini Gusini',
    ability: [
      'Bomber',
      'flight',
      'infinite ammunition and atomic bomb production',
    ],
    motive: ['Fighter', 'goose'],
  },
  {
    source: require('./assets/italian-brainrot/BonecaAmbalabu.jpg'),
    name: 'Boneca Ambalabu',
    ability: ['High jump ability', 'strong kick', 'long tongue'],
    motive: ['Frogs', 'tires', 'legs'],
  },
  {
    source: require('./assets/italian-brainrot/BriiBriiBicusDicusBombicus.jpg'),
    name: 'Brii Brii Bicus Dicus Bombicus',
    ability: ['fence'],
    motive: ['Gladiator', 'birds', 'raspberry'],
  },
  {
    source: require('./assets/italian-brainrot/BrrBrrPatapim.jpg'),
    name: 'Brr Brr Patapim',
    ability: [
      'Forest control',
      'ship installation',
      'ability to change opponents into wood',
    ],
    motive: ['Coju -gu', 'tree', 'foot'],
  },
  {
    source: require('./assets/italian-brainrot/BurbaloniLulilolli.jpg'),
    name: 'Burbaloni Lulilolli',
    ability: ['swimming'],
    motive: ['Capybara', 'Coconut'],
  },
  {
    source: require('./assets/italian-brainrot/CappuccinoAssassino.jpg'),
    name: 'Cappuccino Assassino',
    ability: ['Fast speed', 'katana wielding', 'stealth'],
    motive: ['Capuccino', 'Assassin', 'Circleet'],
  },
  {
    source: require('./assets/italian-brainrot/ChefCrabracadabra.jpg'),
    name: 'Chef Crabracadabra',
    ability: ['Curse'],
    motive: ['Chef', 'Crab', 'Abracada Bra'],
  },
  {
    source: require('./assets/italian-brainrot/ChimpanziniBananini.jpg'),
    name: 'Chimpanzini Bananini',
    ability: ['celerity', 'Bananas peeling off'],
    motive: ['Chimpanzee', 'Banana'],
  },
  {
    source: require('./assets/italian-brainrot/FrigoCamelo.jpg'),
    name: 'Frigo Camelo',
    ability: ['Cold wind spit out'],
    motive: ['Camel', 'refrigerator', 'shoes'],
  },
  {
    source: require('./assets/italian-brainrot/GaramaramanDanMadudungdungTakTuntungPerkuntung.jpg'),
    name: 'Garamaraman DanMadudungdung Tak Tuntung Perkuntung',
    ability: ['unknown'],
    motive: ['Salt barrel', 'honey complex', 'human leg'],
  },
  {
    source: require('./assets/italian-brainrot/GirafaCelestre.jpg'),
    name: 'Girafa Celestre',
    ability: ['Spit watermelon seeds at 50km per second'],
    motive: ['Watermelon', 'giraffe', 'astronaut'],
  },
  {
    source: require('./assets/italian-brainrot/GlorboFruttodrillo.jpg'),
    name: 'Glorbo Fruttodrillo',
    ability: ['snap'],
    motive: ['Crocodile', 'watermelon'],
  },
  {
    source: require('./assets/italian-brainrot/IlCactoHipopotamo.jpg'),
    name: 'Il Cacto Hipopotamo',
    ability: ['step on'],
    motive: ['Hasma', 'cactus', 'sandals'],
  },
  {
    source: require('./assets/italian-brainrot/LaVacaSaturnoSaturnita.jpg'),
    name: 'La Vaca Saturno Saturnita',
    ability: [
      'Mental manipulation',
      'air support',
      'breath Setting and torsion',
    ],
    motive: ['Saturn', 'cattle', 'feet'],
  },
  {
    source: require('./assets/italian-brainrot/LirilìLarilà.jpg'),
    name: 'Lirilì Larilà',
    ability: ['Time stop', 'step on'],
    motive: ['Elephant', 'cactus', 'sandals'],
  },
  {
    source: require('./assets/italian-brainrot/PotHotspot.jpg'),
    name: 'Pot Hotspot',
    ability: ['Hotspot request', 'buy sweets with infinite'],
    motive: ['Skeleton', 'cell phone', 'Wi -Fi', 'hotspot'],
  },
  {
    source: require('./assets/italian-brainrot/SvininoBombondino.jpg'),
    name: 'SvininoBombondino',
    ability: ['self-destruct'],
    motive: ['Pig', 'bomb'],
  },
  {
    source: require('./assets/italian-brainrot/TalpaDiFerro.jpg'),
    name: 'Talpa Di Ferro',
    ability: ['Searching around', 'scan', 'drill'],
    motive: ['Mouse', 'Cyborg'],
  },
  {
    source: require('./assets/italian-brainrot/TaTaTaTaTaTaTaTaTaTaTaSahur.jpg'),
    name: 'Ta Ta Ta Ta Ta Ta Ta Ta Ta Ta Ta Sahur',
    ability: ['Steam creation', 'a great kick'],
    motive: ['kettle'],
  },
  {
    source: require('./assets/italian-brainrot/TralaleroTralala.jpg'),
    name: 'Tralalero Tralala',
    ability: [
      'Wave control',
      'fast running speed',
      'super jump',
      'strong work',
    ],
    motive: ['Shark', 'sneakers'],
  },
  {
    source: require('./assets/italian-brainrot/TricTracBaraboom.jpg'),
    name: 'Tric Trac Baraboom',
    ability: ['Vine whip', 'zucchini'],
    motive: ['Squirrels', 'zucchini', 'feet'],
  },
  {
    source: require('./assets/italian-brainrot/TrippaTroppaTralalaLirilìRilàTungTungSahurBonecaTungTungTralaleloTrippiTroppaCrocodina.jpg'),
    name: 'Trippa Troppa Tralala Lirilì Rilà Tung Tung Sahur Boneca Tung Tung Tralalelo Trippi Troppa Crocodina',
    ability: ['All the ability of brainrot animals'],
    motive: [
      'Tripy Trophy',
      'Tralallaro Tralala',
      'Tung Tung Tung Tung Tung Tung Hur',
      'Boneca Amvalabu',
      'Lirily Larila',
    ],
  },
  {
    source: require('./assets/italian-brainrot/TrippiTroppi.jpg'),
    name: 'Trippi Troppi',
    ability: ['Fast swim', 'wave', 'tsunami', 'cat waves', 'water'],
    motive: ['Shrimp', 'cat'],
  },
  {
    source: require('./assets/italian-brainrot/TrippiTroppi2.jpg'),
    name: 'Trippi Troppi',
    ability: [
      'Bing eating',
      'transformation',
      'Summoning fish',
      'controlled by flies',
    ],
    motive: ['bear', 'fish'],
  },
  {
    source: require('./assets/italian-brainrot/TrulimeroTrulicina.jpg'),
    name: 'Trulimero Trulicina',
    ability: ['Swimming', 'smart brain'],
    motive: ['Fish', 'cat', 'leg'],
  },
  {
    source: require('./assets/italian-brainrot/TungTungTungTungTungTungTungTungTungSahur.jpg'),
    name: 'Tung Tung Tung Tung Tung Tung Tung Tung Tung Sahur',
    ability: ['Giant painting', 'baseball bat swing'],
    motive: ['Baseball bat', 'log'],
  },
  {
    source: require('./assets/italian-brainrot/UDinDinDinDinDunMaDinDinDinDun.jpg'),
    name: 'U Din Din Din Din Dun Ma Din Din Din Dun',
    ability: ['Strong power and grip'],
    motive: ['Orange', 'bodybuilder'],
  },
];
