export default [
  {
    source: require('./assets/italian-brainrot/BallerinaCappuccina.jpg'),
    name: 'Ballerina Cappuccina',
    active: ['ballet'],
    motive: ['Ballerina', 'cappuccino'],
  },
  {
    source: require('./assets/italian-brainrot/BlueberrinniOctopussini.jpg'),
    name: 'Blueberrinni Octopussini',
    active: ['Scaffolding attack', 'fast swimming'],
    motive: ['Blueberry', 'octopus'],
  },
  {
    source: require('./assets/italian-brainrot/BobritoBandito.jpg'),
    name: 'Bobrito Bandito',
    active: [],
    motive: [],
  },
  {
    source: require('./assets/italian-brainrot/BombardiereLucertola.jpg'),
    name: 'Bombardiere Lucertola',
    active: [],
    motive: [],
  },
  {
    source: require('./assets/italian-brainrot/BombardiroCrocodilo.jpg'),
    name: 'Bombardiro Crocodilo',
    active: [],
    motive: [],
  },
  {
    source: require('./assets/italian-brainrot/BombombiniGusini.jpg'),
    name: 'Bombombini Gusini',
    active: [],
    motive: [],
  },
  {
    source: require('./assets/italian-brainrot/BonecaAmbalabu.jpg'),
    name: 'Boneca Ambalabu',
    active: [],
    motive: [],
  },
  {
    source: require('./assets/italian-brainrot/BriiBriiBicusDicusBombicus.jpg'),
    name: 'Brii Brii Bicus Dicus Bombicus',
    active: [],
    motive: [],
  },
  {
    source: require('./assets/italian-brainrot/BrrBrrPatapim.jpg'),
    name: 'Brr Brr Patapim',
    active: [],
    motive: [],
  },
  {
    source: require('./assets/italian-brainrot/BurbaloniLulilolli.jpg'),
    name: 'Burbaloni Lulilolli',
    active: [],
    motive: [],
  },
  {
    source: require('./assets/italian-brainrot/CappuccinoAssassino.jpg'),
    name: 'Cappuccino Assassino',
    active: [],
    motive: [],
  },
  {
    source: require('./assets/italian-brainrot/ChefCrabracadabra.jpg'),
    name: 'Chef Crabracadabra',
    active: [],
    motive: [],
  },
  {
    source: require('./assets/italian-brainrot/ChimpanziniBananini.jpg'),
    name: 'Chimpanzini Bananini',
    active: [],
    motive: [],
  },
  {
    source: require('./assets/italian-brainrot/FrigoCamelo.jpg'),
    name: 'Frigo Camelo',
    active: [],
    motive: [],
  },
  {
    source: require('./assets/italian-brainrot/GaramaramanDanMadudungdungTakTuntungPerkuntung.jpg'),
    name: 'Garamaraman DanMadudungdung Tak Tuntung Perkuntung',
    active: [],
    motive: [],
  },
  {
    source: require('./assets/italian-brainrot/GirafaCelestre.jpg'),
    name: 'Girafa Celestre',
    active: [],
    motive: [],
  },
  {
    source: require('./assets/italian-brainrot/GlorboFruttodrillo.jpg'),
    name: 'Glorbo Fruttodrillo',
    active: [],
    motive: [],
  },
  {
    source: require('./assets/italian-brainrot/IlCactoHipopotamo.jpg'),
    name: 'Il Cacto Hipopotamo',
    active: [],
    motive: [],
  },
  {
    source: require('./assets/italian-brainrot/LaVacaSaturnoSaturnita.jpg'),
    name: 'La Vaca Saturno Saturnita',
    active: [],
    motive: [],
  },
  {
    source: require('./assets/italian-brainrot/LirilìLarilà.jpg'),
    name: 'Lirilì Larilà',
    active: [],
    motive: [],
  },
  {
    source: require('./assets/italian-brainrot/PotHotspot.jpg'),
    name: 'Pot Hotspot',
    active: [],
    motive: [],
  },
  {
    source: require('./assets/italian-brainrot/SvininoBombondino.jpg'),
    name: 'SvininoBombondino',
    active: [],
    motive: [],
  },
  {
    source: require('./assets/italian-brainrot/TalpaDiFerro.jpg'),
    name: 'Talpa Di Ferro',
    active: [],
    motive: [],
  },
  {
    source: require('./assets/italian-brainrot/TaTaTaTaTaTaTaTaTaTaTaSahur.jpg'),
    name: 'Ta Ta Ta Ta Ta Ta Ta Ta Ta Ta Ta Sahur',
    active: [],
    motive: [],
  },
  {
    source: require('./assets/italian-brainrot/TralaleroTralala.jpg'),
    name: 'Tralalero Tralala',
    active: ['Wave control', 'fast running speed', 'super jump', 'strong work'],
    motive: ['Shark', 'sneakers'],
  },
  {
    source: require('./assets/italian-brainrot/TrippaTroppaTralalaLirilìRilàTungTungSahurBonecaTungTungTralaleloTrippiTroppaCrocodina.jpg'),
    name: 'Trippa Troppa Tralala Lirilì Rilà Tung Tung Sahur Boneca Tung Tung Tralalelo Trippi Troppa Crocodina',
    active: [],
    motive: [],
  },
  {
    source: require('./assets/italian-brainrot/TrippiTroppi.jpg'),
    name: 'Trippi Troppi',
    active: [],
    motive: [],
  },
  {
    source: require('./assets/italian-brainrot/TrippiTroppi2.jpg'),
    name: 'Trippi Troppi',
    active: [],
    motive: [],
  },
  {
    source: require('./assets/italian-brainrot/TrulimeroTrulicina.jpg'),
    name: 'Trulimero Trulicina',
    active: [],
    motive: [],
  },
  {
    source: require('./assets/italian-brainrot/TungTungTungTungTungTungTungTungTungSahur.jpg'),
    name: 'Tung Tung Tung Tung Tung Tung Tung Tung Tung Sahur',
    active: [],
    motive: [],
  },
  {
    source: require('./assets/italian-brainrot/UDinDinDinDinDunMaDinDinDinDun.jpg'),
    name: 'U Din Din Din Din Dun Ma Din Din Din Dun',
    active: [],
    motive: [],
  },
];
