export default [
  {
    source: require('./assets/italian-brainrot/BallerinaCappuccina.jpg'),
    name: 'Ballerina Cappuccina',
    ability: ['Ballet'],
    motive: ['Ballerina', 'Cappuccino'],
  },
  {
    source: require('./assets/italian-brainrot/BlueberrinniOctopussini.jpg'),
    name: 'Blueberrinni Octopussini',
    ability: ['Scaffolding attack', 'Fast swimming'],
    motive: ['Blueberry', 'Octopus'],
  },
  {
    source: require('./assets/italian-brainrot/BobritoBandito.jpg'),
    name: 'Bobrito Bandito',
    ability: ['Mass shooting'],
    motive: ['Beaver', 'Thompson submachine gun', 'Gangster', 'Mafia'],
  },
  {
    source: require('./assets/italian-brainrot/BombardiereLucertola.jpg'),
    name: 'Bombardiere Lucertola',
    ability: ['Bomber', 'Flight', 'Camouflage'],
    motive: ['Bomber', 'Lizard'],
  },
  {
    source: require('./assets/italian-brainrot/BombardiroCrocodilo.jpg'),
    name: 'Bombardiro Crocodilo',
    ability: ['Bomber', 'Flight'],
    motive: ['Bomber', 'Crocodile'],
  },
  {
    source: require('./assets/italian-brainrot/BombombiniGusini.jpg'),
    name: 'Bombombini Gusini',
    ability: [
      'Bomber',
      'Flight',
      'Infinite ammunition and atomic bomb production',
    ],
    motive: ['Fighter', 'Goose'],
  },
  {
    source: require('./assets/italian-brainrot/BonecaAmbalabu.jpg'),
    name: 'Boneca Ambalabu',
    ability: ['High jump ability', 'Strong kick', 'Long tongue'],
    motive: ['Frogs', 'Tires', 'Legs'],
  },
  {
    source: require('./assets/italian-brainrot/BriiBriiBicusDicusBombicus.jpg'),
    name: 'Brii Brii Bicus Dicus Bombicus',
    ability: ['Fence'],
    motive: ['Gladiator', 'Birds', 'Raspberry'],
  },
  {
    source: require('./assets/italian-brainrot/BrrBrrPatapim.jpg'),
    name: 'Brr Brr Patapim',
    ability: [
      'Forest control',
      'Ship installation',
      'Ability to change opponents into wood',
    ],
    motive: ['Coju-gu', 'Tree', 'Foot'],
  },
  {
    source: require('./assets/italian-brainrot/BurbaloniLulilolli.jpg'),
    name: 'Burbaloni Lulilolli',
    ability: ['Swimming'],
    motive: ['Capybara', 'Coconut'],
  },
  {
    source: require('./assets/italian-brainrot/CappuccinoAssassino.jpg'),
    name: 'Cappuccino Assassino',
    ability: ['Fast speed', 'Katana wielding', 'Stealth'],
    motive: ['Capuccino', 'Assassin', 'Circleet'],
  },
  {
    source: require('./assets/italian-brainrot/ChefCrabracadabra.jpg'),
    name: 'Chef Crabracadabra',
    ability: ['Curse'],
    motive: ['Chef', 'Crab', 'Abracada Bra'],
  },
  {
    source: require('./assets/italian-brainrot/ChimpanziniBananini.jpg'),
    name: 'Chimpanzini Bananini',
    ability: ['Celerity', 'Bananas peeling off'],
    motive: ['Chimpanzee', 'Banana'],
  },
  {
    source: require('./assets/italian-brainrot/FrigoCamelo.jpg'),
    name: 'Frigo Camelo',
    ability: ['Cold wind spit out'],
    motive: ['Camel', 'Refrigerator', 'Shoes'],
  },
  {
    source: require('./assets/italian-brainrot/GaramaramanDanMadudungdungTakTuntungPerkuntung.jpg'),
    name: 'Garamaraman DanMadudungdung Tak Tuntung Perkuntung',
    ability: ['Unknown'],
    motive: ['Salt barrel', 'Honey complex', 'Human leg'],
  },
  {
    source: require('./assets/italian-brainrot/GirafaCelestre.jpg'),
    name: 'Girafa Celestre',
    ability: ['Spit watermelon seeds at 50km per second'],
    motive: ['Watermelon', 'Giraffe', 'Astronaut'],
  },
  {
    source: require('./assets/italian-brainrot/GlorboFruttodrillo.jpg'),
    name: 'Glorbo Fruttodrillo',
    ability: ['Snap'],
    motive: ['Crocodile', 'Watermelon'],
  },
  {
    source: require('./assets/italian-brainrot/IlCactoHipopotamo.jpg'),
    name: 'Il Cacto Hipopotamo',
    ability: ['Step on'],
    motive: ['Hasma', 'Cactus', 'Sandals'],
  },
  {
    source: require('./assets/italian-brainrot/LaVacaSaturnoSaturnita.jpg'),
    name: 'La Vaca Saturno Saturnita',
    ability: [
      'Mental manipulation',
      'Air support',
      'Breath setting and torsion',
    ],
    motive: ['Saturn', 'Cattle', 'Feet'],
  },
  {
    source: require('./assets/italian-brainrot/LirilìLarilà.jpg'),
    name: 'Lirilì Larilà',
    ability: ['Time stop', 'Step on'],
    motive: ['Elephant', 'Cactus', 'Sandals'],
  },
  {
    source: require('./assets/italian-brainrot/PotHotspot.jpg'),
    name: 'Pot Hotspot',
    ability: ['Hotspot request', 'Buy sweets with infinite'],
    motive: ['Skeleton', 'Cell phone', 'Wi-Fi', 'Hotspot'],
  },
  {
    source: require('./assets/italian-brainrot/SvininoBombondino.jpg'),
    name: 'Svinino Bombondino',
    ability: ['Self-destruct'],
    motive: ['Pig', 'Bomb'],
  },
  {
    source: require('./assets/italian-brainrot/TalpaDiFerro.jpg'),
    name: 'Talpa Di Ferro',
    ability: ['Searching around', 'Scan', 'Drill'],
    motive: ['Mouse', 'Cyborg'],
  },
  {
    source: require('./assets/italian-brainrot/TaTaTaTaTaTaTaTaTaTaTaSahur.jpg'),
    name: 'Ta Ta Ta Ta Ta Ta Ta Ta Ta Ta Ta Sahur',
    ability: ['Steam creation', 'A great kick'],
    motive: ['Kettle'],
  },
  {
    source: require('./assets/italian-brainrot/TralaleroTralala.jpg'),
    name: 'Tralalero Tralala',
    ability: [
      'Wave control',
      'Fast running speed',
      'Super jump',
      'Strong work',
    ],
    motive: ['Shark', 'Sneakers'],
  },
  {
    source: require('./assets/italian-brainrot/TricTracBaraboom.jpg'),
    name: 'Tric Trac Baraboom',
    ability: ['Vine whip', 'Zucchini'],
    motive: ['Squirrels', 'Zucchini', 'Feet'],
  },
  {
    source: require('./assets/italian-brainrot/TrippaTroppaTralalaLirilìRilàTungTungSahurBonecaTungTungTralaleloTrippiTroppaCrocodina.jpg'),
    name: 'Trippa Troppa Tralala Lirilì Rilà Tung Tung Sahur Boneca Tung Tung Tralalelo Trippi Troppa Crocodina',
    ability: ['All the ability of brainrot animals'],
    motive: [
      'Tripy Trophy',
      'Tralallaro Tralala',
      'Tung Tung Tung Tung Tung Tung Hur',
      'Boneca Amvalabu',
      'Lirily Larila',
    ],
  },
  {
    source: require('./assets/italian-brainrot/TrippiTroppi.jpg'),
    name: 'Trippi Troppi',
    ability: ['Fast swim', 'Wave', 'Tsunami', 'Cat waves', 'Water'],
    motive: ['Shrimp', 'Cat'],
  },
  {
    source: require('./assets/italian-brainrot/TrippiTroppi2.jpg'),
    name: 'Trippi Troppi',
    ability: [
      'Bing eating',
      'Transformation',
      'Summoning fish',
      'Controlled by flies',
    ],
    motive: ['Bear', 'Fish'],
  },
  {
    source: require('./assets/italian-brainrot/TrulimeroTrulicina.jpg'),
    name: 'Trulimero Trulicina',
    ability: ['Swimming', 'Smart brain'],
    motive: ['Fish', 'Cat', 'Leg'],
  },
  {
    source: require('./assets/italian-brainrot/TungTungTungTungTungTungTungTungTungSahur.jpg'),
    name: 'Tung Tung Tung Tung Tung Tung Tung Tung Tung Sahur',
    ability: ['Giant painting', 'Baseball bat swing'],
    motive: ['Baseball bat', 'Log'],
  },
  {
    source: require('./assets/italian-brainrot/UDinDinDinDinDunMaDinDinDinDun.jpg'),
    name: 'U Din Din Din Din Dun Ma Din Din Din Dun',
    ability: ['Strong power and grip'],
    motive: ['Orange', 'Bodybuilder'],
  },
];
